version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=121487qw9842191841
      - MONGODB_USER=root
      - MONGODB_PASSWORD=121487qw9842191841
      - MONGODB_DATABASE=donations
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
volumes:
  db: